// Canonical listening content. Used by the seed script; the app keeps a typed
// copy in src/lib/listeningData.ts as an offline fallback.
const M = (s) => `<mark class="bg-emerald-500/20 text-emerald-400 border border-emerald-500/20 px-1.5 py-0.5 rounded font-bold">${s}</mark>`;
const SEC = (n) => `<strong class="text-amber-500 font-mono">[Section ${n}]</strong>`;

export const LISTENING_TESTS = {
  campus: {
    id: "campus",
    title: "Campus Accommodation & Facilities",
    sentences: [
      "Welcome to the student accommodation services.",
      "I am here to help you register.",
      "May I have your name, please?",
      "Yes, it's John Smith. That is S-M-I-T-H.",
      "Great. And your contact number?",
      "It's 0-7-1-2-3-4-5-6-7-8-9.",
      "OK. What type of room are you looking for?",
      "A single room, please.",
      "OK, we have a single room available.",
      "Now let me tell you about our campus facilities.",
      "The library is located in the north building, which is open from 8:00 AM to 10:00 PM daily.",
      "We also have a state-of-the-art sports center next to the library.",
      "It includes an indoor swimming pool, which is heated throughout the year, and a fully equipped gym.",
      "To use the gym, students must attend an induction session first.",
      "Lastly, the student cafeteria is in the central block, serving hot meals from 11:30 AM to 2:30 PM.",
    ],
    transcriptHtml:
      `<p class="mb-2">${SEC(1)} Welcome to the student accommodation services. I am here to help you register. May I have your name, please? Yes, it's John ${M("Smith")} (Q1). That is S-M-I-T-H. Great. And your contact number? It's ${M("07123456789")} (Q2). OK. What type of room are you looking for? A ${M("single")} (Q3) room, please. OK, we have a single room available...</p>` +
      `<p>${SEC(2)} Okay, now let me tell you about our campus facilities. The library is located in the ${M("north building")} (Q4), which is open from 8:00 AM to 10:00 PM daily. We also have a state-of-the-art sports center next to the library. It includes an indoor swimming pool, which is ${M("heated throughout the year")} (Q6), and a fully equipped gym. To use the gym, students must ${M("attend an induction session")} (Q5) first. Lastly, the student cafeteria is in the central block, serving hot meals from ${M("11:30 AM to 2:30 PM")} (Q7).</p>`,
    vocab: [
      { word: "Accommodation", definition: "A room or building in which someone may live.", translation: "Turar joy" },
      { word: "Induction session", definition: "An introductory training or briefing.", translation: "Kirish mashg'uloti" },
      { word: "Heated throughout", definition: "Warmed all year round.", translation: "Yil davomida isitiladigan" },
      { word: "Cafeteria", definition: "A self-service restaurant.", translation: "Oshxona/bufet" },
    ],
    questions: [
      { qid: "q1", kind: "fill", prompt: "Name (Last name)", prefix: "John", suffix: "", answer_key: "SMITH" },
      { qid: "q2", kind: "fill", prompt: "Contact number", prefix: "", suffix: "", answer_key: "07123456789" },
      { qid: "q3", kind: "fill", prompt: "Type of room", prefix: "", suffix: "bedroom", answer_key: "SINGLE" },
      { qid: "q4", kind: "mcq", prompt: "Where is the library located on campus?", options: [{ value: "A", label: "North building" }, { value: "B", label: "South building" }, { value: "C", label: "Central block" }], answer_key: "A" },
      { qid: "q5", kind: "mcq", prompt: "What is required in order to use the gym?", options: [{ value: "A", label: "Pay a monthly fee" }, { value: "B", label: "Attend an induction session" }, { value: "C", label: "Bring your student ID card" }], answer_key: "B" },
      { qid: "q6", kind: "mcq", prompt: "What are the swimming pool heating terms?", options: [{ value: "A", label: "Closed in winter" }, { value: "B", label: "Heated throughout the year" }, { value: "C", label: "Free for all local residents" }], answer_key: "B" },
      { qid: "q7", kind: "mcq", prompt: "When is the cafeteria open for hot meals?", options: [{ value: "A", label: "8:00 AM - 10:00 PM" }, { value: "B", label: "11:30 AM - 2:30 PM" }, { value: "C", label: "All day long" }], answer_key: "B" },
    ],
  },
  travel: {
    id: "travel",
    title: "Travel Agency Booking & City Museum Tour",
    sentences: [
      "Good morning, City Travel Agency. How can I help you?",
      "Yes, I'd like to book a city tour.",
      "Sure. What is your name?",
      "It's Sarah Jenkins. That is J-E-N-K-I-N-S.",
      "OK, Sarah. And your contact number?",
      "It's 0-7-9-8-7-6-5-4-3-2-1.",
      "Great. Which date would you like to tour?",
      "The twelfth of July, please.",
      "Welcome to the City Historical Museum.",
      "Before we start, let me explain the layout.",
      "The main exhibition room is on the second floor, open from 9 AM to 5 PM.",
      "To see the special royal collection, visitors must purchase an extra ticket.",
      "Photography is strictly prohibited inside the collection hall.",
      "Finally, our gift shop is next to the exit, selling souvenirs and booklets from 10 AM to 4 PM.",
    ],
    transcriptHtml:
      `<p class="mb-2">${SEC(1)} Good morning, City Travel Agency. How can I help you? Yes, I'd like to book a city tour. Sure. What is your name? It's Sarah ${M("Jenkins")} (Q1). That is J-E-N-K-I-N-S. OK, Sarah. And your contact number? It's ${M("07987654321")} (Q2). Great. Which date would you like to tour? The ${M("12 JULY")} (Q3) (twelfth of July), please.</p>` +
      `<p>${SEC(2)} Welcome to the City Historical Museum. Before we start, let me explain the layout. The main exhibition room is on the ${M("second floor")} (Q4) (B), open from 9 AM to 5 PM. To see the special royal collection, visitors must ${M("purchase an extra ticket")} (Q5) (A). Photography is ${M("strictly prohibited")} (Q6) (C) inside the collection hall. Finally, our gift shop is next to the exit, selling souvenirs and booklets from ${M("10 AM to 4 PM")} (Q7) (B).</p>`,
    vocab: [
      { word: "Souvenirs", definition: "Things kept as a reminder of a place.", translation: "Esdalik sovg'alari" },
      { word: "Prohibited", definition: "Forbidden by law or rule.", translation: "Taqiqlangan" },
      { word: "Exhibition", definition: "A public display of works of art or items.", translation: "Ko'rgazma" },
      { word: "Souvenir booklet", definition: "A small book with information.", translation: "Esdalik bukleti" },
    ],
    questions: [
      { qid: "q1", kind: "fill", prompt: "Name (Last name)", prefix: "Sarah", suffix: "", answer_key: "JENKINS" },
      { qid: "q2", kind: "fill", prompt: "Contact number", prefix: "", suffix: "", answer_key: "07987654321" },
      { qid: "q3", kind: "fill", prompt: "Date of Tour (e.g. 12 July)", prefix: "", suffix: "", answer_key: "12 JULY" },
      { qid: "q4", kind: "mcq", prompt: "Where is the main exhibition room located?", options: [{ value: "A", label: "First floor" }, { value: "B", label: "Second floor" }, { value: "C", label: "Basement" }], answer_key: "B" },
      { qid: "q5", kind: "mcq", prompt: "What is required to see the royal collection?", options: [{ value: "A", label: "Purchase an extra ticket" }, { value: "B", label: "Join a guided group" }, { value: "C", label: "Leave bags in lockers" }], answer_key: "A" },
      { qid: "q6", kind: "mcq", prompt: "What are the rules regarding photography?", options: [{ value: "A", label: "Allowed everywhere" }, { value: "B", label: "Allowed for a fee" }, { value: "C", label: "Strictly prohibited inside the hall" }], answer_key: "C" },
      { qid: "q7", kind: "mcq", prompt: "When is the gift shop open?", options: [{ value: "A", label: "9:00 AM - 5:00 PM" }, { value: "B", label: "10:00 AM - 4:00 PM" }, { value: "C", label: "All day long" }], answer_key: "B" },
    ],
  },
  career: {
    id: "career",
    title: "Job Interview & Office Orientation",
    sentences: [
      "Hello, HR department of Tech Solutions.",
      "I am calling about my interview tomorrow.",
      "Ah, yes. Can I confirm your name, please?",
      "Yes, it's David Harrison. That is H-A-R-R-I-S-O-N.",
      "Thank you, David. Your contact email is david point h at tech point com?",
      "Yes.",
      "And what position are you interviewing for?",
      "The software engineer position.",
      "Welcome to your first day at Tech Solutions. Let me show you around the office.",
      "The conference room is on the third floor, which is used for all department meetings.",
      "To access the office after 7 PM, employees must use their security badge.",
      "Free parking is available for all staff members in the basement garage.",
      "Lastly, the company kitchen is on the first floor, offering free coffee and snacks from 8:30 AM to 6 PM.",
    ],
    transcriptHtml:
      `<p class="mb-2">${SEC(1)} Hello, HR department of Tech Solutions. I am calling about my interview tomorrow. Ah, yes. Can I confirm your name, please? Yes, it's David ${M("Harrison")} (Q1). That is H-A-R-R-I-S-O-N. Thank you, David. Your contact email is ${M("david.h@tech.com")} (Q2)? Yes. And what position are you interviewing for? The ${M("software engineer")} (Q3) position.</p>` +
      `<p>${SEC(2)} Welcome to your first day at Tech Solutions. Let me show you around the office. The conference room is on the ${M("third floor")} (Q4) (A), which is used for all department meetings. To access the office after 7 PM, employees must ${M("use their security badge")} (Q5) (C). Free parking is available for all staff members in the ${M("basement garage")} (Q6) (A). Lastly, the company kitchen is on the first floor, offering free coffee and snacks from ${M("8:30 AM to 6:00 PM")} (Q7) (B).</p>`,
    vocab: [
      { word: "Orientation", definition: "Introduction to a new workplace.", translation: "Moslashuv/tanishuv" },
      { word: "HR department", definition: "Human Resources department.", translation: "Kadrlar bo'limi" },
      { word: "Security badge", definition: "A card allowing access to a building.", translation: "Ruxsatnoma beyjigi" },
      { word: "Garage", definition: "A building or shed for housing motor vehicles.", translation: "Avtoturargoh" },
    ],
    questions: [
      { qid: "q1", kind: "fill", prompt: "Name (Last name)", prefix: "David", suffix: "", answer_key: "HARRISON" },
      { qid: "q2", kind: "fill", prompt: "Contact email", prefix: "", suffix: "", answer_key: "DAVID.H@TECH.COM" },
      { qid: "q3", kind: "fill", prompt: "Applied Position", prefix: "the", suffix: "position", answer_key: "SOFTWARE ENGINEER" },
      { qid: "q4", kind: "mcq", prompt: "Where is the conference room located?", options: [{ value: "A", label: "Third floor" }, { value: "B", label: "First floor" }, { value: "C", label: "Penthouse" }], answer_key: "A" },
      { qid: "q5", kind: "mcq", prompt: "What is required to access the office after 7 PM?", options: [{ value: "A", label: "Enter a passcode" }, { value: "B", label: "Sign in with security" }, { value: "C", label: "Use their security badge" }], answer_key: "C" },
      { qid: "q6", kind: "mcq", prompt: "Where can staff park their cars for free?", options: [{ value: "A", label: "Basement garage" }, { value: "B", label: "Street parking" }, { value: "C", label: "Nearby public lot" }], answer_key: "A" },
      { qid: "q7", kind: "mcq", prompt: "When is the kitchen open for coffee and snacks?", options: [{ value: "A", label: "24 hours a day" }, { value: "B", label: "8:30 AM - 6:00 PM" }, { value: "C", label: "Only during lunch hours" }], answer_key: "B" },
    ],
  },
  clinic: {
    id: "clinic",
    title: "Health Centre Appointment & Facilities",
    sentences: [
      "Good morning, City Health Centre. How can I help you?",
      "I'd like to book an appointment, please.",
      "Of course. Can I take your name?",
      "It's Emma Taylor. That is T-A-Y-L-O-R.",
      "And a contact number?",
      "It's 0-7-7-0-0-9-0-0-1-2-3.",
      "What is the appointment for?",
      "A dental check-up, please.",
      "Welcome to the health centre. Let me explain a few things.",
      "The pharmacy is on the ground floor, open until 8 PM.",
      "To see a specialist, you need a referral from your doctor.",
      "Blood tests are done only in the morning, before 11 AM.",
      "Finally, the car park is free for the first two hours.",
    ],
    transcriptHtml:
      `<p class="mb-2">${SEC(1)} Good morning, City Health Centre. How can I help you? I'd like to book an appointment, please. Can I take your name? It's Emma ${M("Taylor")} (Q1). That is T-A-Y-L-O-R. And a contact number? It's ${M("07700900123")} (Q2). What is the appointment for? A ${M("dental")} (Q3) check-up, please.</p>` +
      `<p>${SEC(2)} Welcome to the health centre. The pharmacy is on the ${M("ground floor")} (Q4) (A), open until 8 PM. To see a specialist, you need a ${M("referral from your doctor")} (Q5) (A). Blood tests are done only in the morning, ${M("before 11 AM")} (Q6) (B). Finally, the car park is free for the first ${M("two hours")} (Q7) (B).</p>`,
    vocab: [
      { word: "Referral", definition: "A letter directing a patient to a specialist.", translation: "Yo'llanma" },
      { word: "Specialist", definition: "A doctor highly skilled in a specific field.", translation: "Mutaxassis shifokor" },
      { word: "Pharmacy", definition: "A place where medicines are prepared and sold.", translation: "Dorixona" },
      { word: "Check-up", definition: "A thorough medical examination.", translation: "Tibbiy ko'rik" },
    ],
    questions: [
      { qid: "q1", kind: "fill", prompt: "Name (Last name)", prefix: "Emma", suffix: "", answer_key: "TAYLOR" },
      { qid: "q2", kind: "fill", prompt: "Contact number", prefix: "", suffix: "", answer_key: "07700900123" },
      { qid: "q3", kind: "fill", prompt: "Appointment type", prefix: "", suffix: "check-up", answer_key: "DENTAL" },
      { qid: "q4", kind: "mcq", prompt: "Where is the pharmacy located?", options: [{ value: "A", label: "Ground floor" }, { value: "B", label: "First floor" }, { value: "C", label: "Basement" }], answer_key: "A" },
      { qid: "q5", kind: "mcq", prompt: "What is needed to see a specialist?", options: [{ value: "A", label: "A referral from your doctor" }, { value: "B", label: "An online booking" }, { value: "C", label: "A photo ID" }], answer_key: "A" },
      { qid: "q6", kind: "mcq", prompt: "When are blood tests done?", options: [{ value: "A", label: "In the afternoon" }, { value: "B", label: "Before 11 AM" }, { value: "C", label: "Any time" }], answer_key: "B" },
      { qid: "q7", kind: "mcq", prompt: "How long is parking free?", options: [{ value: "A", label: "One hour" }, { value: "B", label: "Two hours" }, { value: "C", label: "All day" }], answer_key: "B" },
    ],
  },
  restaurant: {
    id: "restaurant",
    title: "Restaurant Booking & Information",
    sentences: [
      "Good evening, The Riverside Restaurant.",
      "Hi, I'd like to book a table for Saturday.",
      "Certainly. What name shall I put it under?",
      "It's David Clark. That is C-L-A-R-K.",
      "And a phone number in case we need to reach you?",
      "Yes, it's 0-7-9-1-1-1-2-3-4-5-6.",
      "Welcome to The Riverside. Let me tell you about tonight.",
      "The main dining area is on the first floor, with river views.",
      "Our special tonight is grilled salmon, served until 9 PM.",
      "To use the private room, a deposit of fifty pounds is required.",
      "Lastly, live music starts at 8 PM every Saturday.",
    ],
    transcriptHtml:
      `<p class="mb-2">${SEC(1)} Good evening, The Riverside Restaurant. I'd like to book a table for ${M("Saturday")} (Q3). What name shall I put it under? It's David ${M("Clark")} (Q1). That is C-L-A-R-K. And a phone number? Yes, it's ${M("07911123456")} (Q2).</p>` +
      `<p>${SEC(2)} Welcome to The Riverside. The main dining area is on the ${M("first floor")} (Q4) (B), with river views. Our special tonight is ${M("grilled salmon")} (Q5) (A), served until 9 PM. To use the private room, a ${M("deposit")} (Q6) (A) of fifty pounds is required. Lastly, live music starts at ${M("8 PM")} (Q7) (B).</p>`,
    vocab: [
      { word: "Deposit", definition: "A sum paid in advance as a guarantee.", translation: "Oldindan to'lov/zakalat" },
      { word: "Reservation", definition: "An arrangement to have something kept for you.", translation: "Bron qilish" },
      { word: "Cuisine", definition: "A style or method of cooking.", translation: "Oshpazlik uslubi" },
      { word: "Venue", definition: "The place where an event happens.", translation: "Joy/maskan" },
    ],
    questions: [
      { qid: "q1", kind: "fill", prompt: "Name (Last name)", prefix: "David", suffix: "", answer_key: "CLARK" },
      { qid: "q2", kind: "fill", prompt: "Contact number", prefix: "", suffix: "", answer_key: "07911123456" },
      { qid: "q3", kind: "fill", prompt: "Day of booking", prefix: "", suffix: "", answer_key: "SATURDAY" },
      { qid: "q4", kind: "mcq", prompt: "Where is the main dining area?", options: [{ value: "A", label: "Ground floor" }, { value: "B", label: "First floor" }, { value: "C", label: "Garden terrace" }], answer_key: "B" },
      { qid: "q5", kind: "mcq", prompt: "What is tonight's special?", options: [{ value: "A", label: "Grilled salmon" }, { value: "B", label: "Roast chicken" }, { value: "C", label: "Vegetable curry" }], answer_key: "A" },
      { qid: "q6", kind: "mcq", prompt: "What is required to use the private room?", options: [{ value: "A", label: "A deposit" }, { value: "B", label: "A membership" }, { value: "C", label: "Formal dress" }], answer_key: "A" },
      { qid: "q7", kind: "mcq", prompt: "When does live music start?", options: [{ value: "A", label: "7 PM" }, { value: "B", label: "8 PM" }, { value: "C", label: "9 PM" }], answer_key: "B" },
    ],
  },
  college: {
    id: "college",
    title: "Evening Course Enrolment",
    sentences: [
      "Hello, Riverside Community College.",
      "Hi, I'm interested in enrolling in an evening course.",
      "Great. May I have your name?",
      "It's Laura White. That is W-H-I-T-E.",
      "And a contact number?",
      "It's 0-7-8-0-0-1-2-3-4-5-6.",
      "Which course are you interested in?",
      "The photography course, please.",
      "Welcome to the college. Here is some information.",
      "Classes are held in the main building, room 12.",
      "To get a student discount, you must show a valid ID.",
      "The course materials are provided free of charge.",
      "Finally, the library is open until 9 PM on weekdays.",
    ],
    transcriptHtml:
      `<p class="mb-2">${SEC(1)} Hello, Riverside Community College. I'm interested in enrolling in an evening course. May I have your name? It's Laura ${M("White")} (Q1). That is W-H-I-T-E. And a contact number? It's ${M("07800123456")} (Q2). Which course? The ${M("photography")} (Q3) course, please.</p>` +
      `<p>${SEC(2)} Welcome to the college. Classes are held in the ${M("main building, room 12")} (Q4) (A). To get a student discount, you must show a ${M("valid ID")} (Q5) (A). The course materials are ${M("provided free of charge")} (Q6) (A). Finally, the library is open until ${M("9 PM")} (Q7) (B) on weekdays.</p>`,
    vocab: [
      { word: "Enrol", definition: "To officially register as a member or student.", translation: "Ro'yxatdan o'tmoq" },
      { word: "Discount", definition: "A reduction in the usual price.", translation: "Chegirma" },
      { word: "Materials", definition: "Items needed for a particular activity.", translation: "O'quv materiallari" },
      { word: "Weekdays", definition: "The days from Monday to Friday.", translation: "Ish kunlari" },
    ],
    questions: [
      { qid: "q1", kind: "fill", prompt: "Name (Last name)", prefix: "Laura", suffix: "", answer_key: "WHITE" },
      { qid: "q2", kind: "fill", prompt: "Contact number", prefix: "", suffix: "", answer_key: "07800123456" },
      { qid: "q3", kind: "fill", prompt: "Course", prefix: "", suffix: "course", answer_key: "PHOTOGRAPHY" },
      { qid: "q4", kind: "mcq", prompt: "Where are classes held?", options: [{ value: "A", label: "Room 12, main building" }, { value: "B", label: "The annex" }, { value: "C", label: "Online only" }], answer_key: "A" },
      { qid: "q5", kind: "mcq", prompt: "What is needed for a student discount?", options: [{ value: "A", label: "A valid ID" }, { value: "B", label: "A booking reference" }, { value: "C", label: "A deposit" }], answer_key: "A" },
      { qid: "q6", kind: "mcq", prompt: "What is provided free of charge?", options: [{ value: "A", label: "Course materials" }, { value: "B", label: "Lunch" }, { value: "C", label: "Parking" }], answer_key: "A" },
      { qid: "q7", kind: "mcq", prompt: "When does the library close on weekdays?", options: [{ value: "A", label: "6 PM" }, { value: "B", label: "9 PM" }, { value: "C", label: "Midnight" }], answer_key: "B" },
    ],
  },
};
